### ISSUE TITLE
C++ version of coordinate-parser

### ISSUE THREAD

**Issue by Fabiz** [servant-of-god/coordinate-parser#11]
Hi Otto

I just released a C++ clone of your great coordinate-parser under https://github.com/Fabiz/CoordinateParserCpp. I did reference your work and also the original implementation from [WEPROG](http://www.weprog.com/). 
The code is also licensed under http://www.apache.org/licenses/LICENSE-2.0.

I hope this is ok for your. Otherwise please tell me and I'll remove it from Github immediately.

best regards
Fabio

**Comment by otto-dev** [comment]
I'm flattered, and yes, this should be totally all right from my side. Thank you.

Just to give you a bit of a picture: Back in the day (seven years ago now), I just informally asked if my client at the time, WEPROG, if they wanted to open-source this piece of code, and they were happy to give permission. To my best recollection they did not attach any conditions. So I may have made certain choices (in respect to attribution etc) in good faith rather than by requirement when setting up the repo, knowing also that they were open-source enthusiasts.

So yes, by all means. Maybe we would also link to your repo from the `README`.

**Comment by Fabiz** [comment]
Great! Thanks a lot for your work and for the permission. It was a straightforward task to create the C++ version with your Javascript code.
